[package]
name = "wasm-gzip"
version = "1.0.1"
authors = ["ColinTimBarndt <colin.barndt@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/ColinTimBarndt/wasm-gzip"
description = "Compress and decompress data on the web using WebAssembly."
keywords = ["wasm", "gzip", "compression", "web"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
libflate = "1.0"
js-sys = "0.3.47"

[profile.release]
opt-level = "s"